[[redirects]]
from = "/clientes/nuevo"
to = "/estudiante/:id"
status = 200
force = true

[[redirects]]
  from = "/clientes/nuevo"
  to = "/estudiante/:id"
  status = 302

[build]
  publish = "public"
